(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Afternoon Iain, Welcome to Coot version 0.9.8.95")
(use-graphics-interface-state)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 30.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-map 0.00)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle 1.00)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good afternoon Iain. Welcome to Coot 0.9.8.95")
(set-display-lists-for-maps 1)
(set-show-symmetry-master 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "/localdata/iain/_local/projectB/exports/dimers_replaced/1XLS_GH_replaced.pdb" 1)
(use-graphics-interface-state)
