filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Afternoon Iain, Welcome to Coot version 0.9.8.95")
use_graphics_interface_state ()
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (30.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_map (0.00)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle (1.00)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good afternoon Iain. Welcome to Coot 0.9.8.95")
set_display_lists_for_maps (1)
set_show_symmetry_master (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("/localdata/iain/_local/projectB/exports/dimers_replaced/1XLS_GH_replaced.pdb", 1)
use_graphics_interface_state ()
